apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "terraform-mcp-server.fullname" . }}-config
  labels:
    {{- include "terraform-mcp-server.labels" . | nindent 4 }}
data:
{{- range .Values.env }}
  {{ .name }}: {{ .value | quote }}
{{- end }}