apiVersion: v1
kind: Secret
metadata:
  name: {{ include "terraform-mcp-server.fullname" . }}-secret
  labels:
    {{- include "terraform-mcp-server.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range .Values.secretEnv }}
  {{ .name }}: {{ .value | quote }}
{{- end }}