apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-servers.fullname" . }}-secret
  labels:
    {{- include "mcp-servers.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.terraform.env.secret }}
  {{- if $value }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}