apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-servers.fullname" . }}
  labels:
    {{- include "mcp-servers.labels" . | nindent 4 }}
spec:
  type: {{ .Values.terraform.service.type }}
  ports:
    - port: {{ .Values.terraform.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mcp-servers.selectorLabels" . | nindent 4 }}
